# Ubuntu 20.04 static configuration
network:
    ethernets:
        enp0s3:
            dhcp4: no
            dhcp6: no
            addresses: [192.168.0.40/24]
            gateway4: 192.168.0.1
            nameservers:
               addresses: [1.1.1.1]
    version: 2
